<a href="https://colab.research.google.com/github/luis10095/C8280/blob/CDR/Activity2/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

NumPy es la librería central para computación científica en Python. Proporciona un objeto de matriz multidimensional de alto rendimiento y herramientas para trabajar con estas matrices.

#### Matrices

Una matriz NumPy es una colección de valores de tipos de datos similares y está indexada por una tupla de números no negativos. El rango de la matriz es el número de dimensiones, y la forma de una matriz es una tupla de números que dan el tamaño de la matriz a lo largo de cada dimensión.


In [2]:
# Ejemplo
from __future__ import division
import time
import numpy as np


tam_vec = 1000
def lista_python():
    t1 = time.time()
    X = range(tam_vec)
    Y = range(tam_vec)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1

def matriz_numpy():
    t1 = time.time()
    X = np.arange(tam_vec)
    Y = np.arange(tam_vec)
    Z = X + Y
    return time.time() - t1

# Completar

t1 = lista_python()
t2 = matriz_numpy()
print(
    t1,t2,
    f'\nLa relacion de t1/t2 e: {t1/t2} más rápido'
    )


0.0016748905181884766 0.004589557647705078 
La relacion de t1/t2 e: 0.36493506493506495 más rápido


In [ ]:
#import numpy
#numpy.__version__

#para conocer la version de la librería de np  como que el que tenga trabahar pq

np.__version__

'1.22.4'

Podemos inicializar matrices NumPy a partir de listas de Python anidadas y acceder a los elementos mediante corchetes.

In [ ]:
# Creamos una matriz de rango 1
a = np.array([0, 1, 2])
print (type(a))
a
# Imprimimos la dimension de la matriz
print (a.shape)
print (a[0])
print (a[1])
print (a[2])

# Cambiamos un elemento de un array
a[0] = 5
print (a)

<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]


In [ ]:
# Creamos una matriz de rango 2
b = np.array([[0,1,2],[3,4,5]])
print (b.shape)
print (b)
print (b[0, 0], b[0, 1], b[1, 0])

(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


In [ ]:
print ( b.shape)
print ( b[0, 0], b[0, 1], b[1, 0])

(2, 3)
0 1 3


### Creación de una matriz NumPy

NumPy también proporciona muchas funciones integradas para crear matrices. La mejor manera de aprender esto es a través de ejemplos, así que pasemos al código.

In [ ]:
# Creamos una matriz 3x3 de todos ceros
a = np.zeros((3,3))
print (a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Creamos una matriz 2x2 de todos 1
b = np.ones((2,2))
print (b)

[[1. 1.]
 [1. 1.]]


In [ ]:
# Creamos una matriz 3x3 constantes
c = np.full((3,3), 7)
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
# Creamos una matriz 3x3 con valores aleatorios
d = np.random.random((3,3))
print (d)

[[0.25059777 0.09740732 0.410975  ]
 [0.79736374 0.78257688 0.54962997]
 [0.56485314 0.53095035 0.88754938]]


In [ ]:
# Creamos una matriz identidad 3x3
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Convertir una lista en una matriz
f = np.array([2, 3, 1,0])
print(f)

[2 3 1 0]


In [ ]:
# arange() crea matrices con valores que se incrementan regularmente
# Completar
g = np.arange(5,25,dtype=float);g
h = np.linspace(5,50,num = 7,endpoint=True, dtype = float);h

array([ 5. , 12.5, 20. , 27.5, 35. , 42.5, 50. ])

In [ ]:
# Mezcla de tupla y listas
# Completar
k_k = ((1,3,5,7))
o_o = ([2,4,6,8])

union = np.concatenate((k_k, o_o))
union

array([1, 3, 5, 7, 2, 4, 6, 8])

In [ ]:
# Crear una matriz de rango con tipo de datos flotante
i = np.arange(1, 8, dtype=np.float64)
print(i)

[1. 2. 3. 4. 5. 6. 7.]


`linspace()`  crea matrices con un numero especifico de elementos que están espaciados por igual entre los valores inicial y final especificados

In [ ]:
# Completa
ln = np.linspace(0,50,num = 10,dtype = float)
ln

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

### Tipos de datos
Una matriz es una colección de elementos del mismo tipo de datos y NumPy admite y proporciona funciones integradas para construir matrices con argumentos opcionales para especificar explícitamente los tipos de datos requeridos.

In [ ]:
# Numpy escoge el tipo de datos
x = np.array([0, 1])
y = np.array([2.0, 3.0])

# Fuerza un tipo de datos en particular
z = np.array([5, 6], dtype=np.int64)
print (x.dtype, y.dtype, z.dtype)

int64 float64 int64


 **Ejercicio** Completa el siguiente  código.

In [ ]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)  # matriz 1-d
x2 = np.random.randint(10, size=(5, 4))  # matriz-2d
x3 = np.random.randint(10, size=(2, 4, 5)) # matriz-3d

#https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#numpy.linspace
# Imprime los atributos : dim, shape, size, dtype, itemsize y nbytes
#https://note.nkmk.me/en/python-numpy-ndarray-ndim-shape-size/

# Completar
'''
alto vias, bajo vias
algoritmos suérvisados
sbm con kernels
arboles de decision
'''

#para conocer la idmension de una array de numoy es necesario con ndim
dim1 = x1.ndim
dim2 = x2.ndim
dim3 = x3.ndim

#shape: return the shape of on array
shap1 = np.shape(x1)
shap2 = np.shape(x2)
shap3 = np.shape(x3)

##size: return the number of elements along a give axis
size1 = np.size(x1)
size2 = np.size(x2)
size3 = np.size(x3)

#type
types = type(x3),type(x2), type(x1);types

#itemsize: length of one array element in bytes
itemsizes = x1.itemsize, x2.itemsize, x3.itemsize;itemsizes

#nbyte: total bytes consumed by elements of the array
nbyte = x1.nbytes, x2.nbytes, x3.nbytes; nbyte


(48, 160, 320)

In [ ]:
dim3,dim2,dim1


6

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7],
       [8, 1, 5, 9],
       [8, 9, 4, 3]])

### Indexación de matrices

NumPy ofrece varias formas de indexar en matrices. La sintaxis estándar de Python `x[obj]` se puede usar para indexar la matriz NumPy, donde `x` es la matriz y `obj` es la selección.

Hay tres tipos de indexación disponibles:

* Acceso al campo

* Recorte básico

* Indexación avanzada

#### Acceso al campo

Si el objeto ndarray es una matriz estructurada, se puede acceder a los campos de la matriz indexando la matriz con cadenas, como un diccionario. La indexación de `x['field-name']` devuelve una nueva vista de la matriz, que tiene la misma dimensión que `x`, excepto cuando el campo es una submatriz  que contiene sólo la parte de los datos en el campo especificado. Los tipos de datos se obtienen con `x.dtype['field-name']`. 562+

In [ ]:
x = np.zeros((3,3), dtype=[('a', np.int32), ('b', np.float64, (3,3))])
print(x)


[[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]
 [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]
 [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]]


In [ ]:
print ("x['a'].shape: ",x['a'].shape)
print ("x['a'].dtype: ", x['a'].dtype)

print ("x['b'].shape: ", x['b'].shape)
print ("x['b'].dtype: ", x['b'].dtype)

x['a'].shape:  (3, 3)
x['a'].dtype:  int32
x['b'].shape:  (3, 3, 3, 3)
x['b'].dtype:  float64


#### Recorte básico

Las matrices NumPy se pueden dividir, de forma similar a las listas. Debe especificar un segmento para cada dimensión de la matriz, ya que las matrices pueden ser multidimensionales.

La sintaxis de división básica es `i: j: k`, donde `i` es el índice inicial, `j` es el índice final, `k` es el paso y `k` no es igual a 0. Esto selecciona los elementos `m` en la dimensión correspondiente, con valores de índice `, i + k, ...,i + (m - 1)k` donde `m = q + (r distinto de 0)`,  `q` y `r` son el cociente y el resto se obtiene dividiendo `j - i` entre `k`: `j - i = qk + r`, de modo que `i + (m - 1) k < j`.

In [3]:
x = np.array([5, 6, 7, 8, 9])
x[1:7:2]

array([6, 8])

La `k` negativa hace que los pasos vayan hacia índices más pequeños. Los `i` y `j` negativos se interpretan como `n + i` y `n + j` donde `n` es el número de elementos en la dimensión correspondiente.

In [4]:
print (x[-2:5])
print (x[-1:1:-1])

[8 9]
[9 8 7]


Si `n` es el número de elementos en la dimensión que se está recortando. Entonces, si no se proporciona `i`, el valor predeterminado es `0` para  `k > 0` y `n-1` para `k < 0`. Si no se proporciona `j`, el valor predeterminado es `n` para `k > 0` y `-1` para `k < 0`. Si no se proporciona `k`, el valor predeterminado es `1`. Ten en cuenta que `::` es lo mismo que `:` y significa seleccionar todos los índices a lo largo de este eje.

In [5]:
x[2:]

array([7, 8, 9])

Si el número de objetos en la tupla de selección es menor que N , entonces se asume `:` para cualquier dimensión subsiguiente.

In [ ]:
# Completar
'''
puedo hacer un recorte que es lo mismo con la representacion x[1::]
'''
x[2]


7

Los puntos suspensivos se expanden al número de : objetos necesarios para hacer una tupla de selección de la misma longitud que `x.ndim`. Solo puede haber una sola elipsis presente.

In [ ]:
print(x)

In [6]:
x[...,4]

array(9)

#### Ejercicio

1. Crea una matriz de rango `2` con dimension `(3, 4)`

2. Usa el recorte para extraer la submatriz que consta de las primeras `2` filas y las columnas `1` y `2`.

3. Una parte de una matriz es solo una vista de los mismos datos, comprueba quecualquier modificación modificará la matriz original.



In [7]:
# Tu respuesta
mat = np.random.randint(10,50, (3,4))
new = mat[:2,1:3]
print(mat)
new

[[19 23 17 18]
 [48 35 10 45]
 [49 20 28 40]]


array([[23, 17],
       [35, 10]])

Se puede acceder a la matriz de la fila central de dos maneras.

* Las partes junto con la indexación de enteros darán como resultado una matriz de rango inferior.

* El uso de solo recortes dará como resultado el mismo rango matriz.

In [8]:
# Creamos una matriz de rango 2 array con dimensión (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Dos formas de acceder a los datos en la fila central de la matriz. La combinación de la indexación de enteros con recortes produce una matriz de menor rango, mientras que el uso de solo recortes produce una matriz del mismo rango que la matriz original:

In [9]:
fila_r1 = a[1, :]    # Vista de rango 1 de la segunda fila de a
fila_r2 = a[1:2, :]  # Vista de rango 2 de la segunda fila de a
fila_r3 = a[[1], :]  # Vista de ranfo 2 de la segunda fila de a
print (fila_r1, fila_r1.shape)
print (fila_r2, fila_r2.shape)
print (fila_r3, fila_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


Podemos hacer la misma distinción al acceder a las columnas de una matriz.

In [10]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print (col_r1, col_r1.shape)
print (col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


### Indexación avanzada


In [15]:
a = np.array([[1,2], [3, 4]])
print (a[[0, 1], [0, 1]])

# El ejemplo de indexacion de una matriz entera es equivalente a esto:
# completar
#nos fijamos que es un recorte de la diagonal de la matriz
print(np.diagonal(a))

[1 4]
[1 4]


Al usar la indexacion de un matriz de enteros, puede reutilizar el mismo elemento de la matriz de origen:

In [32]:
print (a[[0, 0], [1, 1]])

# Equivalente al ejemplo de indexacion de matriz de enteros
# completar
print(np.repeat(a[0,1],2))

[2 2]
[2 2]


Un asunto  importante y extremadamente útil acerca de los recortes de una  matriz es que devuelven  *vistas (`views`)* en lugar de *copias (`copies`)*  de los datos de la matriz. Este es un área en la que NumPy  difiere de la lista de Python:  en las listas, estas son copias.

In [ ]:
np.random.seed(0)
x2 = np.random.randint(10, size=(5, 4))
x2

In [ ]:
x2_sub = x2[:2, :2]
print(x2_sub)

In [ ]:
x2_sub[0, 0] = 99
print(x2_sub)

Este comportamiento predeterminado es realmente muy útil: significa que cuando trabajamos con grandes conjuntos de datos, podemos acceder y procesar partes de estos conjuntos de datos sin necesidad de copiar el búfer de datos.

A pesar de las características  de las `vistas` de una  matriz, a veces es útil copiar de forma explícita los datos dentro de una matriz o una submatriz. Esto se puede hacer  con el método `copy()`:

In [ ]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

In [ ]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

In [ ]:
print(x2)

### Reshaping

In [ ]:
x4 = np.arange(1, 10).reshape((3, 3))
print(x4)

Ten en cuenta que para que esto funcione, el tamaño de la matriz inicial debe coincidir con el tamaño de la matriz rediseñada. Siempre que sea posible, el método `reshape` utilizará una `vista` sin copia de la matriz inicial.

Otro patrón de `reshaping `, es la conversión de una matriz unidimensional en una fila o columna de una matriz bidimensional. Esto se puede hacer con el método `reshape`  o más fácilmente haciendo uso de `newaxis` dentro de una operación de división:

In [ ]:
x5 = np.array([1, 2, 3])
x5

In [ ]:
# vector fila via reshape
# completar

In [ ]:
# vector fila con newaxis
# completar

In [ ]:
# vector columna via reshape
# completar

In [ ]:
# vector columna con newaxis
# completar

### Concatenación y  separación


In [ ]:
x = np.array([4, 5, 6])
y = np.array([7, 8, 9])
np.concatenate([x, y])

In [ ]:
# concatenacion de dos o mas matrices
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

In [ ]:
# concatendo una matriz dos veces
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid])

Para trabajar con matrices de distintas dimensiones, se usan las funciones `vstack` y `hstack`:

In [ ]:
x = np.array([0, 1, 2])
grid = np.array([[3, 4, 5],
                 [6, 5, 4]])

# Se junta la matriz de manera vertical
# Completar

In [ ]:
# Se junta la matriz de manera horizontal
y = np.array([[23],
              [23]])
# Completar

Lo contrario de la concatenación es la división o separación, que es implementado por las funciones `np.split`, `np.hsplit` y `np.vsplit`. Para cada uno de estas funciones , podemos pasar una lista de índices que dan los puntos de división.

Ver:[https://numpy.org/doc/stable/reference/generated/numpy.split.html](https://numpy.org/doc/stable/reference/generated/numpy.split.html)

In [ ]:
x = [1, 2, 3, 44, 95, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

In [ ]:
grid = np.arange(16).reshape((4, 4))
grid

In [ ]:
grid1, grid2 = np.vsplit(grid, [2])
print(grid1)
print(grid2)

In [ ]:
grid3, grid4 = np.hsplit(grid,[2])
print(grid3)
print(grid4)

### Fancy


In [ ]:
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
print(x)

In [ ]:
# Accedemos a tres elementos diferentes
[x[1], x[5], x[2]]

Alternativamente, podemos pasar una sola lista o matriz de índices para obtener el mismo resultado:

In [ ]:
# Completar

Cuando se utiliza fancy, la forma del resultado refleja la forma de las matrices de índice en lugar de la forma de la matriz que se indexa y trabaja  en múltiples  dimensiones:

In [ ]:
# Completar

In [ ]:
X = np.arange(12).reshape((3, 4))
X

Al igual que con la indexación estándar, el primer índice se refiere a la fila, y el segundo a la columna:

In [ ]:
fila = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[fila, col]

Observa que el primer valor en el resultado es `X[0, 2]`, el segundo es `X[1, 1]`  y el tercero es `X[2, 3]`. El emparejamiento de índices en la indexación fancy  sigue todas las reglas del broadcasting, por ejemplo, si combinamos un vector de columna y un vector de fila dentro de los índices, obtenemos un resultado bidimensional:

In [ ]:
# Completar

Aquí, cada valor de fila se empareja con cada vector de columna, exactamente como se hace en broadcasting  de operaciones aritméticas. Por ejemplo:

In [ ]:
# Completar

Siempre es importante recordar que en  la indexación fancy, el valor de retorno refleja la forma del broadcasting  de los índices, en lugar de la forma de la matriz que se indexa.

Para operaciones  más potentes, la indexación adornada se puede combinar con los otros esquemas de indexación que existen:

In [ ]:
# print(X)

In [ ]:
# Combinando el indexado fancy y indices simples
# Completar

In [ ]:
# Combinando el indexado fancy y el recorte
# Completar

Así como el fancy  se puede utilizar para acceder a partes de una matriz, también se puede utilizar para modificar partes de una matriz. Por ejemplo, si  tenemos una matriz de índices y nos gustaría establecer los elementos correspondientes en una matriz a algún valor, podemos hacer lo siguiente:

In [ ]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

Los índices repetidos con estas operaciones pueden causar algunos resultados potencialmente inesperados. Considera lo siguiente:

In [ ]:
x = np.zeros(10)
x[[0, 0]] = [4, 6]
print(x)

El resultado de esta operación es asignar primero  `x[0] = 4`, seguido por `x[0] = 6`. Pero el resultado es que `x[0]` contiene el valor 6.

Considera la siguiente operación:

In [ ]:
i = [2, 3, 3, 4, 4, 4]
x[i] += 1
x

En este caso algún resultado inesperado se debe conceptualmente  a que `x[i] +=1` se entiende como una abreviatura de `x[i] = x [i] + 1`. Cuando `x[i] + 1` es evaluado el resultado es asignado  a los índices en `x` . Con esto en mente, no es que el aumento que ocurre varias veces, sino la asignación, que conduce a los resultados  no intuitivos.

Si quieremos  el otro comportamiento donde se repite la operación, se puede utilizar el método `at()` de `ufuncs`:

In [ ]:
# Completar

El método `at()` realiza una aplicación  del operador dado en los índices especificados (aquí, `i`) con el valor especificado (aquí, `1`).

###  Expresiones vectorizadas

### Agregaciones


In [ ]:
L = np.random.random(100)
sum(L)

La sintaxis es bastante similar a la función de `sum` de  `NumPy`  y el resultado es el mismo en el caso más simple:

In [ ]:
np.sum(L)

Sin embargo, debido a que la operación se ejecuta  en código compilado, la versión `NumPy` de la operación se calcula mucho más rápidamente:

In [ ]:
matriz_grande = np.random.rand(1000000)
%timeit sum(matriz_grande)
%timeit np.sum(matriz_grande)

La función `sum` y la función `np.sum` no son idénticas, lo que a veces puede conducir a la confusión.  En particular, sus argumentos opcionales tienen significados diferentes  y `np.sum` es válido a  varias dimensiones de una matriz.

In [ ]:
# Otras funciones min y max
min(matriz_grande), max(matriz_grande)

In [ ]:
%timeit min(matriz_grande)
%timeit np.min(matriz_grande)

Todas estas funciones también están disponibles como métodos en la clase `ndarray`. Por ejemplo, `np.mean(data)` y `data.mean()` en el ejemplo siguiente son equivalentes:

In [ ]:
data = np.random.normal(size=(15, 15))
np.mean(data)

In [ ]:
data.mean()

Un tipo común de operación de agregación es un agregado a lo largo de una fila o columna.

In [ ]:
M = np.random.random((5, 6))
print(M)

De forma predeterminada, cada función de agregación de  `NumPy`  devolverá el agregado sobre toda la matriz:

In [ ]:
M.sum()

Las funciones de agregación toman un argumento adicional que especifica el eje a lo largo del cual se calcula el agregado. Por ejemplo, podemos encontrar el valor de la suma y el  mínimo de cada columna especificando `axis = 0`:

In [ ]:
M.sum(axis= 0)

In [ ]:
data = np.random.normal(size=(5, 10, 15))
data.sum(axis=0).shape

In [ ]:
data.sum(axis=(0, 2)).shape

In [ ]:
data.sum()

Algunas funciones de agregación en `Numpy ` son :


|Nombre de funcion  | VersionNaN-safe     | Descripcion                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Calcula suma de elementos                     |
| ``np.prod``       | ``np.nanprod``      | Calcula el producto de elementos              |
| ``np.mean``       | ``np.nanmean``      | Calcula la media de elementos                 |
| ``np.std``        | ``np.nanstd``       | Calcula la desviacion estandar                |
| ``np.var``        | ``np.nanvar``       | Calcula la  varianza                          |
| ``np.min``        | ``np.nanmin``       | Encuentra el minimo valor                     |
| ``np.max``        | ``np.nanmax``       | Encuentra el maximo valor                     |
| ``np.argmin``     | ``np.nanargmin``    | Encuenta el index del minimo valor            |
| ``np.argmax``     | ``np.nanargmax``    | Encuentra el index del maximo valor           |
| ``np.median``     | ``np.nanmedian``    | Calcula la mediana de elementos               |
| ``np.percentile`` | ``np.nanpercentile``| Calcula el rango estatistico de elementos     |
| ``np.any``        | N/A                 | Evalua si algun elemento es true              |
| ``np.all``        | N/A                 | Evalua si todos los elementos son true        |



#### Broadcasting


In [ ]:
a = np.array([0, 1, 2])
b = np.array([2, 6, 1])
a + b

El  `broadcasting` permite que estos tipos de operaciones binarias se realicen en matrices de diferentes tamaños; por ejemplo, podemos añadir  un escalar (una matriz de dimensión cero) a una matriz:

In [ ]:
a + 5


Podemos extender de manera similar esto a matrices de mayor dimensión. Veamos el resultado cuando agregamos una matriz unidimensional a una matriz bidimensional:

In [ ]:
A = np.arange(16).reshape(4, 4)
b = np.arange(4)
A

In [ ]:
A + b

Podemos aplicar el  `broadcasting` en dos matrices. Considere el siguiente ejemplo:

In [ ]:
# Completar

In [ ]:
# Completar

In [ ]:
# Completar

In [ ]:
# Completar

###  Regla del broadcasting

El `broadcasting` en `NumPy` sigue un estricto conjunto de reglas para determinar la interacción entre dos matrices :

* Regla 1: Si las dos matrices difieren en su número de dimensiones, la forma de la matriz que tiene menos dimensiones se rellena con unos en el lado principal (izquierdo).

* Regla 2: Si la forma de los dos matrices no coincide con ninguna dimensión, la matriz con la forma igual a 1 en esa dimensión se estira para que coincida con la otra dimensión.

* Regla 3: Si en cualquier dimensión los tamaños son distintos y ninguno es igual a 1, se genera un error.

### Un útil truco:

In [ ]:
J = np.arange(0, 40, 10)
J.shape

In [ ]:
J = J[:, np.newaxis]  # agregamos un nuevo eje ->  matriz 2D
J.shape

In [ ]:
J

In [ ]:
J + 3

### Comparaciones, máscaras y lógica Booleana


In [ ]:
a1 = np.array([1, 2, 3, 4])
b1 = np.array([4, 3, 2, 1])
a1 < b1

In [ ]:
np.all(a1 < b1)

In [ ]:
np.any(a1 < b1)

In [ ]:
if np.all(a1 < b1):
    print(" Todos los elementos en a1 son menores que los elementos en b1 ")
elif np.any(a1 < b1):
    print("Algunos elementos en a1 son menores que los elementos de b1")
else:
    print("Todos los elementos en b1 son menores que los elementos de a1")

Al aparecer en una expresión aritmética junto con un número escalar, u otra matriz `NumPy` con un tipo de datos numéricos, una matriz booleana se convierte en una matriz numérica con valores `0` y `1` en lugar de `False` y `True`, respectivamente.

In [ ]:
# Completar

In [ ]:
# Completar

In [ ]:
# Completar

Esta es una propiedad útil para la computación condicional, como cuando se definen funciones.

In [ ]:
#def pulso(t, posicion, altura, ancho):
#    return altura * (t >= posicion) * (t <= (posicion + ancho))
# Completar

### Matrices booleanas como máscaras

Revisar: [masked array](https://docs.scipy.org/doc/numpy/reference/maskedarray.html).

In [ ]:
k = np.array([1, 3, -1, 5, 7, -1])
mask = (k < 0)
mask

In [ ]:
# Un ejemplo bidimensional
rng = np.random.RandomState(0)
z1 = rng.randint(10, size=(3, 4))
z1

In [ ]:
# Completar

Ahora, para seleccionar estos valores de la matriz, podemos simplemente indexar en esta matriz booleana, esto se conoce como una operación de `enmascaramiento`:

In [ ]:
# Completar

El siguiente ejemplo muestra cómo sumar la matriz de enmascaramiento,  donde `True` representa uno y `False` representa 0.

In [ ]:
# Completar

### Lectura recomendada: [Numpy Reference](https://docs.scipy.org/doc/numpy/reference/).